### ISSUE TITLE
这个用的是老的context的接口吗?

### ISSUE THREAD

**Issue by Qpumpkin** [rsuite/form-lib#2]
我也在设计一个form组件, 有点看不懂,constructor还有第二个参数context ? 新版本的父元素貌似没法绑定this.props.children里的元素的value了.

**Comment by simonguo** [comment]
@Qpumpkin  你可以参考 rsuite 中的 [Form](https://github.com/rsuite/rsuite/blob/master/src/Form.js)
或者直接使用, [文档](https://rsuitejs.com/components/form) 。
